Waterflow routing algorithm
JuliaGeodynamics/GeophysicalModelGenerator.jl pull request #131
Opened 2024-07-01 19:22 UTC by boriskaus

This adds a water flow routing algorithm to a topographic dataset imported with `import_topo`. We use the package [WhereTheWaterFlows.jl](https://github.com/mauro3/WhereTheWaterFlows.jl) for this:

Usage:
```Julia
julia> using GeophysicalModelGenerator, GMT, GLMakie
julia> Topo = import_topo([6.5,7.3,50.2,50.6], file="@earth_relief_03s");

# Flow the water through the area:
julia> Topo_water, sinks, pits, bnds  = waterflows(Topo)
julia> Topo_water
GeoData 
  size      : (961, 481, 1)
  lon       ϵ [ 6.5 : 7.3]
  lat       ϵ [ 50.2 : 50.59999999999999]
  depth     ϵ [ 0.045 : 0.724]
  fields    : (:Topography, :area, :slen, :dir, :nout, :nin, :c)

julia> heatmap(Topo_water.lon.val[:,1], Topo_water.lat.val[1,:], log10.(Topo_water.fields.area[:,:,1]))
```

<img width="1160" alt="Screenshot 2024-07-01 at 21 21 34" src="https://github.com/JuliaGeodynamics/GeophysicalModelGenerator.jl/assets/61824822/becf7ab8-c759-475b-b43e-4bf3c5dbd408">

2024-07-01 19:36 UTC, aelligp approved these changes
Looks good. Thanks for implementing this

2024-07-02 11:26 UTC, albert-de-montserrat requested changes

2024-07-02 11:26 UTC, albert-de-montserrat commented on src/WaterFlow.jl
> +    dlat = zero(lat.val[:,:,1])
```suggestion
    dlon = zero(size(lon.val)[1:2])
    dlat = zero(size(lat.val)[1:2])
```
This will avoid allocating two intermediate arrays

2024-07-02 11:26 UTC, albert-de-montserrat commented on src/WaterFlow.jl
> +    dlat[:,1], dlat[:,end] = dlat[:,2], dlat[:,end-1]
```suggestion
    @views dlon[2:end-1,:] = (lon.val[3:end,:,1] - lon.val[1:end-2,:,1])/2
    @views dlon[1,:], dlon[end,:] = dlon[2,:], dlon[end-1,:]
    @views dlat[:,2:end-1] = (lat.val[:,3:end,1] - lat.val[:,1:end-2,1])/2
    @views dlat[:,1], dlat[:,end] = dlat[:,2], dlat[:,end-1]
```

2024-07-02 11:26 UTC, albert-de-montserrat commented on src/WaterFlow.jl
> +    c       = zeros(Int64,size(Topo.depth.val))
```suggestion
    ni      = size(Topo.depth.val)
    area    = zeros(ni)
    slen    = zeros(Int64, ni)
    dir     = zeros(Int8, ni)
    nout    = zeros(Int8, ni)
    nin     = zeros(Int8, ni)
    c       = zeros(Int64, ni)
```

2024-07-02 11:26 UTC, albert-de-montserrat commented on src/WaterFlow.jl
> +    area[:,:,1], slen[:,:,1], dir[:,:,1], nout[:,:,1], nin[:,:,1], sinks, pits, c[:,:,1], bnds = waterflows(dem, cellarea, flowdir_fn;
```suggestion
    @views area[:,:,1], slen[:,:,1], dir[:,:,1], nout[:,:,1], nin[:,:,1], sinks, pits, c[:,:,1], bnds = waterflows(dem, cellarea, flowdir_fn;
```

2024-07-03 15:08 UTC, albert-de-montserrat approved these changes
Looks good to me! Just a random dot that could be removed

2024-07-03 15:08 UTC, albert-de-montserrat commented on src/WaterFlow.jl
> +    area_m2 = dx.*dy*1e6
```suggestion
    area_m2 = dx*dy*1e6
```

2024-07-03 19:01 UTC, merged