Contribution_2
JuliaGeodynamics/GeophysicalModelGenerator.jl pull request #154
Opened 2024-12-11 14:39 UTC by adbayonao

I added the script Ridge.jl in Contribution_2 folder.

This script allows for modeling complex oceanic ridge configurations, supporting multiple ridge segments and enabling the calculation of temperature variations based on ridge spreading, age, and thermal properties.

2025-01-19 17:09 UTC, boriskaus commented on src/.Setup_geometry.jl.swm
I'm not sure why this file is added

2025-01-19 17:09 UTC, boriskaus commented on src/.Setup_geometry.jl.swn
this seems unnecessary

2025-01-19 17:09 UTC, boriskaus commented on src/.Setup_geometry.jl.swo
this too

2025-01-19 19:26 UTC, albert-de-montserrat requested changes

2025-01-19 19:26 UTC, albert-de-montserrat commented on Project.toml
> +Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
```suggestion
```
Revise should not be in the Project.toml

2025-01-19 19:26 UTC, albert-de-montserrat commented on src/Setup_geometry.jl
> +    zlim_ = Float64.(collect(zlim))
```suggestion
    xlim_ = collect(xlim)
    ylim_ = collect(ylim)
    zlim_ = collect(zlim)
```
Is the `Float64` conversion really needed for any reason? otherwise it's better to be generic.

2025-01-19 19:26 UTC, albert-de-montserrat commented on src/Setup_geometry.jl
> +    ind_slice = zeros(Bool, size(X[:, :, 1]))
```suggestion
    ind_slice = zeros(Bool, size(X,3))
```

2025-01-19 19:26 UTC, albert-de-montserrat commented on src/Setup_geometry.jl
> +    for k = 1:size(Z)[3]
```suggestion
    for k = 1:size(Z, 3)
```

2025-01-19 19:26 UTC, albert-de-montserrat commented on src/Setup_geometry.jl
> +        if Z[1, 1, k] >= zlim_[1] && Z[1, 1, k] <= zlim_[2]
```suggestion
        if zlim_[1] <= Z[1, 1, k] <= zlim_[2]
```

2025-01-19 19:26 UTC, albert-de-montserrat commented on src/Setup_geometry.jl
> +            ind[:, :, k] = ind_slice
```suggestion
            @views ind[:, :, k] .= ind_slice
```

2025-01-19 19:26 UTC, albert-de-montserrat commented on src/Setup_geometry.jl
> +            ind[:, :, k] = zeros(size(X[:, :, 1]))
```suggestion
            @views ind[:, :, k] .= zeros(size(X, 3))
```

2025-01-19 19:26 UTC, albert-de-montserrat commented on src/Setup_geometry.jl
> +        ThermalAge = abs(Distance * 1e3 * 1e2) / SpreadingVel + AgeRidge * 1e6  # Thermal age in years
```suggestion
        ThermalAge = abs(Distance * 1e5) / SpreadingVel + AgeRidge * 1e6  # Thermal age in years
```

2025-01-19 19:26 UTC, albert-de-montserrat commented on src/Setup_geometry.jl
> +    end
```suggestion
    direction == :left ? side > 0 : side < 0
```

2025-01-19 19:26 UTC, albert-de-montserrat commented on src/Setup_geometry.jl
> +        end
```suggestion
        # Determine the direction of the segments
        direction = x2 < x1 ? :left : :right
```

2025-01-19 19:26 UTC, albert-de-montserrat commented on test/test_ridge_segments.jl
> +    @test all(Temp .<= 1350.0)  # Ensure no temperatures above max
```suggestion
    @test all(≥(0),    Temp) # Ensure no negative temperatures
    @test all(≤(1350), Temp) # Ensure no temperatures above max
```

2025-01-19 19:26 UTC, albert-de-montserrat commented on test/test_ridge_segments.jl
> +    @test Phases[end, end, end] == 2  # Example: Verify another point's phase
```suggestion
    @test first(Phases) == 2  # Example: Verify a point's phase
    @test last(Phases)  == 2  # Example: Verify another point's phase
```

2025-01-20 14:11 UTC, adbayonao commented on src/Setup_geometry.jl
> +    zlim_ = Float64.(collect(zlim))
Thank you. I will change it to be generic.

2025-01-20 14:13 UTC, adbayonao commented on src/Setup_geometry.jl
> +    for k = 1:size(Z)[3]
Ok, thank you. I will do this modification.

2025-01-20 14:14 UTC, adbayonao commented on src/Setup_geometry.jl
> +    ind_slice = zeros(Bool, size(X[:, :, 1]))
I initially followed the structure of the add_polygon! function, which uses the approach of setting ind_slice = zeros(Bool, size(X[:,1,:])). This ensures compatibility with the inpolygon! function. Changing this to size(X, 3) would result in dimension mismatches and errors, as observed in the tests. Therefore, I believe the current implementation is necessary for proper functionality.

2025-01-20 14:25 UTC, adbayonao commented on src/Setup_geometry.jl
> +        if Z[1, 1, k] >= zlim_[1] && Z[1, 1, k] <= zlim_[2]
Thank you. I will do this modification.

2025-01-20 14:25 UTC, adbayonao commented on src/Setup_geometry.jl
> +            ind[:, :, k] = ind_slice
Thank you. I will do this modification.

2025-01-20 14:25 UTC, adbayonao commented on src/Setup_geometry.jl
> +            ind[:, :, k] = zeros(size(X[:, :, 1]))
Thank you. I will do this modification.

2025-01-20 14:52 UTC, adbayonao commented on Project.toml
> +Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Thank you. I will restore the Project.toml file

2025-02-20 11:34 UTC, aelligp approved these changes
Looks good to me, thank you for your contribution

2025-02-20 12:36 UTC, merged